declare const _default: import("vue").DefineComponent<{
    readonly data: import("../../../utils/props").BuildPropReturn<ObjectConstructor, unknown, unknown, unknown, true>;
    readonly props: import("../../../utils/props").BuildPropReturn<import("../../../utils/props").PropWrapper<Partial<import("../../../utils/types").IKeysObject>>, unknown, unknown, () => {
        id: string;
        pid: string;
        label: string;
        expand: string;
        children: string;
    }, unknown>;
    readonly toolBar: import("../../../utils/props").BuildPropReturn<readonly [ObjectConstructor, BooleanConstructor], unknown, unknown, () => {
        expand: boolean;
        scale: boolean;
        zoom: boolean;
        restore: boolean;
        fullscreen: boolean;
    }, unknown>;
    readonly disabled: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, false, unknown>;
    readonly scalable: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly draggable: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly draggableOnNode: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, false, unknown>;
    readonly nodeDraggable: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly cloneNodeDrag: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly onlyOneNode: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly clickDelay: import("../../../utils/props").BuildPropReturn<NumberConstructor, unknown, unknown, 260, unknown>;
    readonly defaultExpandLevel: NumberConstructor;
    readonly nodeDragStart: FunctionConstructor;
    readonly nodeDraging: FunctionConstructor;
    readonly beforeDragEnd: FunctionConstructor;
    readonly nodeDragEnd: FunctionConstructor;
    readonly horizontal: BooleanConstructor;
    readonly selectedKey: import("../../../utils/props").BuildPropReturn<readonly [ArrayConstructor, StringConstructor, NumberConstructor], unknown, unknown, unknown, unknown>;
    readonly collapsable: BooleanConstructor;
    readonly renderContent: FunctionConstructor;
    readonly labelStyle: ObjectConstructor;
    readonly labelClassName: import("../../../utils/props").BuildPropReturn<readonly [FunctionConstructor, StringConstructor], unknown, unknown, unknown, unknown>;
    readonly selectedClassName: import("../../../utils/props").BuildPropReturn<readonly [FunctionConstructor, StringConstructor], unknown, unknown, unknown, unknown>;
    readonly defineMenus: import("../../../utils/props").BuildPropReturn<import("../../../utils/props").PropWrapper<import("../../../utils/types").DefineMenus | import("../../../utils/types").IMenu[]>, unknown, unknown, () => {
        name: string;
        command: string;
    }[], unknown>;
    readonly nodeAdd: FunctionConstructor;
    readonly nodeDelete: FunctionConstructor;
    readonly nodeEdit: FunctionConstructor;
    readonly nodeCopy: FunctionConstructor;
    readonly filterNodeMethod: FunctionConstructor;
}, {
    keys: {
        id: string;
        pid: string;
        label: string;
        expand: string;
        children: string;
    };
    left: import("vue").Ref<number>;
    top: import("vue").Ref<number>;
    menuX: import("vue").Ref<number>;
    menuY: import("vue").Ref<number>;
    nodeMoving: import("vue").Ref<boolean>;
    zoomStyle: import("vue").ComputedRef<{
        width: string;
        height: string;
        transform: string;
    }>;
    tools: {
        visible: boolean;
        data: {
            expand: boolean;
            scale: boolean;
            zoom: boolean;
            restore: boolean;
            fullscreen: boolean;
        };
    };
    zoomPercent: import("vue").ComputedRef<string>;
    dragCancel: import("vue").ComputedRef<"" | ".tree-org-node__content:not(.is-root)>.tree-org-node__inner">;
    expandTitle: import("vue").ComputedRef<"收起全部节点" | "展开全部节点">;
    fullTiltle: import("vue").ComputedRef<"收起全部节点" | "展开全部节点">;
    nodeargs: import("vue").ComputedRef<{
        drag: boolean;
        dragData: {
            keys: {
                id: string;
                pid: string;
                label: string;
                expand: string;
                children: string;
            };
            nodeMoving: import("vue").Ref<boolean>;
            parenNode: {
                value: {
                    id: string | number;
                    pid: string | number;
                    label: string;
                    expand: boolean;
                    $$data: Record<string, any>;
                    $$level: number;
                    $$root?: boolean | undefined;
                    $$focused?: boolean | undefined;
                    isLeaf?: boolean | undefined;
                    hidden?: boolean | undefined;
                    disabled?: boolean | undefined;
                    moving?: boolean | undefined;
                    focused?: boolean | undefined;
                    style?: any;
                    className?: string | undefined;
                    children?: any[] | undefined;
                } | null;
            };
            cloneNodeDrag: boolean;
            onlyOneNode: boolean;
            contextmenu: import("vue").Ref<boolean>;
            cloneData: import("vue").Ref<{}>;
            data: Record<string, any>;
        };
        handleStart: Function | undefined;
        handleMove: Function | undefined;
        beforeDragEnd: Function | undefined;
        handleEnd: Function | undefined;
    }>;
    expanded: import("vue").Ref<boolean>;
    fullscreen: import("vue").Ref<boolean>;
    treeData: import("vue").Ref<{
        id: string | number;
        pid: string | number;
        label: string;
        expand: boolean;
        $$data: Record<string, any>;
        $$level: number;
        $$root?: boolean | undefined;
        $$focused?: boolean | undefined;
        isLeaf?: boolean | undefined;
        hidden?: boolean | undefined;
        disabled?: boolean | undefined;
        moving?: boolean | undefined;
        focused?: boolean | undefined;
        style?: any;
        className?: string | undefined;
        children?: any[] | undefined;
    }>;
    autoDragging: import("vue").Ref<boolean>;
    contextmenu: import("vue").Ref<boolean>;
    nodeMenus: import("vue").Ref<{
        name: string;
        command: string;
    }[]>;
    menuData: import("vue").Ref<{
        id: string | number;
        pid: string | number;
        label: string;
        expand: boolean;
        $$data: Record<string, any>;
        $$level: number;
        $$root?: boolean | undefined;
        $$focused?: boolean | undefined;
        isLeaf?: boolean | undefined;
        hidden?: boolean | undefined;
        disabled?: boolean | undefined;
        moving?: boolean | undefined;
        focused?: boolean | undefined;
        style?: any;
        className?: string | undefined;
        children?: any[] | undefined;
    }>;
    cloneData: import("vue").Ref<{}>;
    filter: (value: any) => void;
    setData: (data: Record<string, any>) => void;
    zoomWheel: (e: WheelEvent) => void;
    onDrag: (x: number, y: number) => void;
    onDragStop: (x: number, y: number) => void;
    expandChange: () => void;
    handleFullscreen: (e: string) => void;
    zoomOrgchart: (zoom: number) => void;
    restoreOrgchart: () => void;
    handleExpand: (e: MouseEvent, node: import("../../../utils/types").INode) => void;
    nodeMouseenter: (e: MouseEvent, node: import("../../../utils/types").INode) => boolean;
    nodeMouseleave: (e: MouseEvent, node: import("../../../utils/types").INode) => boolean;
    nodeContextmenu: (e: MouseEvent, node: import("../../../utils/types").INode) => void;
    handleBlur: (e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => void;
    handleClick: (e: MouseEvent, node: import("../../../utils/types").INode) => void;
    handleDblclick: (e: MouseEvent, node: import("../../../utils/types").INode) => void;
    eleRef: import("vue").Ref<HTMLElement | undefined>;
    treeRef: import("vue").Ref<HTMLElement | undefined>;
    zoomRef: import("vue").Ref<HTMLElement | undefined>;
    defaultSlot: boolean;
    expandSlot: boolean;
}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {
    'on-drag': ({ x, y }: Record<string, number>) => boolean;
    'on-drag-stop': ({ x, y }: Record<string, number>) => boolean;
    'on-restore': () => boolean;
    'on-zoom': (val: number) => boolean;
    'on-expand': (e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => boolean;
    'on-expand-all': (bool: boolean) => boolean;
    'on-node-blur': (e: FocusEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => boolean;
    'on-node-click': (e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => boolean;
    'on-node-dblclick': (e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => boolean;
    'on-node-mouseenter': (e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => boolean;
    'on-node-mouseleave': (e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => boolean;
    'on-contextmenu': (data: any) => boolean;
    'on-node-copy': (str: string) => boolean;
    'on-node-delete': (node: import("../../../utils/types").INode) => boolean;
    'on-node-focus': (e: FocusEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => boolean;
}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
    readonly data: import("../../../utils/props").BuildPropReturn<ObjectConstructor, unknown, unknown, unknown, true>;
    readonly props: import("../../../utils/props").BuildPropReturn<import("../../../utils/props").PropWrapper<Partial<import("../../../utils/types").IKeysObject>>, unknown, unknown, () => {
        id: string;
        pid: string;
        label: string;
        expand: string;
        children: string;
    }, unknown>;
    readonly toolBar: import("../../../utils/props").BuildPropReturn<readonly [ObjectConstructor, BooleanConstructor], unknown, unknown, () => {
        expand: boolean;
        scale: boolean;
        zoom: boolean;
        restore: boolean;
        fullscreen: boolean;
    }, unknown>;
    readonly disabled: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, false, unknown>;
    readonly scalable: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly draggable: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly draggableOnNode: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, false, unknown>;
    readonly nodeDraggable: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly cloneNodeDrag: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly onlyOneNode: import("../../../utils/props").BuildPropReturn<BooleanConstructor, unknown, unknown, true, unknown>;
    readonly clickDelay: import("../../../utils/props").BuildPropReturn<NumberConstructor, unknown, unknown, 260, unknown>;
    readonly defaultExpandLevel: NumberConstructor;
    readonly nodeDragStart: FunctionConstructor;
    readonly nodeDraging: FunctionConstructor;
    readonly beforeDragEnd: FunctionConstructor;
    readonly nodeDragEnd: FunctionConstructor;
    readonly horizontal: BooleanConstructor;
    readonly selectedKey: import("../../../utils/props").BuildPropReturn<readonly [ArrayConstructor, StringConstructor, NumberConstructor], unknown, unknown, unknown, unknown>;
    readonly collapsable: BooleanConstructor;
    readonly renderContent: FunctionConstructor;
    readonly labelStyle: ObjectConstructor;
    readonly labelClassName: import("../../../utils/props").BuildPropReturn<readonly [FunctionConstructor, StringConstructor], unknown, unknown, unknown, unknown>;
    readonly selectedClassName: import("../../../utils/props").BuildPropReturn<readonly [FunctionConstructor, StringConstructor], unknown, unknown, unknown, unknown>;
    readonly defineMenus: import("../../../utils/props").BuildPropReturn<import("../../../utils/props").PropWrapper<import("../../../utils/types").DefineMenus | import("../../../utils/types").IMenu[]>, unknown, unknown, () => {
        name: string;
        command: string;
    }[], unknown>;
    readonly nodeAdd: FunctionConstructor;
    readonly nodeDelete: FunctionConstructor;
    readonly nodeEdit: FunctionConstructor;
    readonly nodeCopy: FunctionConstructor;
    readonly filterNodeMethod: FunctionConstructor;
}>> & {
    "onOn-drag"?: ((args_0: Record<string, number>) => any) | undefined;
    "onOn-drag-stop"?: ((args_0: Record<string, number>) => any) | undefined;
    "onOn-restore"?: (() => any) | undefined;
    "onOn-zoom"?: ((val: number) => any) | undefined;
    "onOn-expand"?: ((e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => any) | undefined;
    "onOn-expand-all"?: ((bool: boolean) => any) | undefined;
    "onOn-node-blur"?: ((e: FocusEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => any) | undefined;
    "onOn-node-click"?: ((e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => any) | undefined;
    "onOn-node-dblclick"?: ((e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => any) | undefined;
    "onOn-node-mouseenter"?: ((e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => any) | undefined;
    "onOn-node-mouseleave"?: ((e: MouseEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => any) | undefined;
    "onOn-contextmenu"?: ((data: any) => any) | undefined;
    "onOn-node-copy"?: ((str: string) => any) | undefined;
    "onOn-node-delete"?: ((node: import("../../../utils/types").INode) => any) | undefined;
    "onOn-node-focus"?: ((e: FocusEvent, data: Record<string, any>, node: import("../../../utils/types").INode) => any) | undefined;
}, {
    readonly props: Partial<import("../../../utils/types").IKeysObject>;
    readonly toolBar: boolean | Record<string, any>;
    readonly disabled: boolean;
    readonly scalable: boolean;
    readonly draggable: boolean;
    readonly draggableOnNode: boolean;
    readonly nodeDraggable: boolean;
    readonly cloneNodeDrag: boolean;
    readonly onlyOneNode: boolean;
    readonly clickDelay: number;
    readonly horizontal: boolean;
    readonly selectedKey: string | number | unknown[];
    readonly collapsable: boolean;
    readonly labelClassName: string | Function;
    readonly selectedClassName: string | Function;
    readonly defineMenus: import("../../../utils/types").DefineMenus | import("../../../utils/types").IMenu[];
}>;
export default _default;
